name: Build OpenWrt IPK
on:
  workflow_dispatch:  # 保持手动触发
  push:
    paths:
      - '.github/workflows/openwrt-curl-http3.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 恢复原 SDK 下载步骤（简化版）
      - name: Download SDK
        run: |
          SDK_URL="https://downloads.openwrt.org/releases/24.10.2/targets/x86/64/openwrt-sdk-24.10.2-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst"
          wget $SDK_URL -O openwrt-sdk.tar.zst
          sudo apt install -y zstd
          tar --use-compress-program=zstd -xf openwrt-sdk.tar.zst
          SDK_DIR=$(find . -name "openwrt-sdk-*" -type d | head -n 1)
          echo "SDK_DIR=$SDK_DIR" >> $GITHUB_ENV

      - name: Debug SDK
        run: |
          echo "SDK_DIR: ${{ env.SDK_DIR }}"
          ls ${{ env.SDK_DIR }}
