name: Build OpenWrt x86_64 QUIC/TLS IPK

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/openwrt-curl-http3.yml'

jobs:
  build-ipk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Init package feed structure
        run: |
          bash ./package_feed_init.sh  # 生成 quictls 等目录的 Makefile

      # ↓↓↓ 替换此处为新的 SDK 下载&解压步骤 ↓↓↓
      - name: Download & Extract OpenWrt SDK (x86_64, 24.10.2)
        run: |
          SDK_URL="https://downloads.openwrt.org/releases/24.10.2/targets/x86/64/openwrt-sdk-24.10.2-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst"
          wget $SDK_URL -O openwrt-sdk.tar.zst
          sudo apt update && sudo apt install -y zstd  # 安装 ZSTD 工具
          tar --use-compress-program=zstd -xf openwrt-sdk.tar.zst  # 解压 .zst
          SDK_DIR=$(find . -name "openwrt-sdk-*" -type d | head -n 1)
          echo "SDK_DIR=$SDK_DIR" >> $GITHUB_ENV
      # ↑↑↑ 新 SDK 步骤结束 ↑↑↑

      - name: Link package to SDK
        run: |
          ln -s $GITHUB_WORKSPACE/openwrt-curl-http3-feed/quictls ${{ env.SDK_DIR }}/package/quictls

      - name: Compile IPK for x86_64
        run: |
          cd ${{ env.SDK_DIR }}
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make package/quictls/compile V=s -j4  # 编译 quictls 包

      - name: Collect generated IPK
        run: |
          mkdir -p $GITHUB_WORKSPACE/ipk-output
          find ${{ env.SDK_DIR }}/bin/packages -name "quictls_*.ipk" -exec cp {} $GITHUB_WORKSPACE/ipk-output/ \;

      - name: Upload IPK as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: quictls-ipk-x86_64
          path: ${{ github.workspace }}/ipk-output/*.ipk
          retention-days: 30

      - name: Optional: Commit IPK to repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ipk-output/
          git commit -m "Auto-generate quictls IPK (x86_64)" || echo "No new IPK"
          git push https://${{ secrets.HTTP_3_QUIC_TLS_ipk }}@github.com/yhcwwcc-boop/HTTP-3-QUIC-TLS_ipk.git main
