name: Build OpenWrt IPK
on:
  workflow_dispatch:  # 必须保留，否则无手动触发按钮
  push:
    paths:
      - '.github/workflows/openwrt-curl-http3.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug
        run: |
          echo "Workflow triggered successfully!"
          ls -l
