name: Init OpenWrt HTTP3/QUIC/TLS Package Feed

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/openwrt-curl-http3.yml'

jobs:
  setup-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # 关键：禁用默认凭据，避免冲突

      - name: Init package feed structure for OpenWrt curl+HTTP3
        run: |
          bash ./package_feed_init.sh

      - name: Commit & push generated feed
        run: |
          # 配置用户信息
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # 添加生成的文件
          git add openwrt-curl-http3-feed/
          
          # 提交（无变更则跳过）
          git commit -m "Auto-generate package feed" || echo "No changes to commit"
          
          # 强制使用你的密钥推送（确保仓库地址和密钥名称正确）
          git push https://${{ secrets.HTTP_3_QUIC_TLS_ipk }}@github.com/yhcwwcc-boop/HTTP-3-QUIC-TLS_ipk.git main
