name: Init OpenWrt HTTP3/QUIC/TLS Package Feed

on:
  workflow_dispatch:  # 允许手动触发
  push:
    paths:
      - '.github/workflows/openwrt-curl-http3.yml'  # 仅当工作流文件修改时自动触发

jobs:
  setup-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Init package feed structure for OpenWrt curl+HTTP3
        run: |
          bash ./package_feed_init.sh  # 执行初始化脚本

      - name: Commit & push generated feed
        run: |
          # 配置提交用户信息（固定为GitHub Actions机器人）
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # 添加生成的目录到暂存区
          git add openwrt-curl-http3-feed
          
          # 提交变更（如果有新内容）
          git commit -m "Auto: Generate OpenWrt curl/HTTP3/quictls/ngtcp2/nghttp3 package feed" || echo "Nothing to commit"
          
          # 使用自定义密钥推送（核心修改：替换为你的密钥名和仓库地址）
          git push https://${{ secrets.HTTP_3_QUIC_TLS_ipk }}@github.com/yhcwwcc-boop/HTTP-3-QUIC-TLS_ipk.git main
